### ISSUE TITLE
Failure on OSX nightly

### ISSUE THREAD

**Issue by timholy** [fhs/ZipFile.jl#17] opened 2015-09-26 17:19 UTC
https://travis-ci.org/timholy/Images.jl/builds/82309190 illustrates a reliable (happens every time) failure that appears to be due to ZipFile. The key failure appears to be about 2/3 of the way down, in `_find_diroffset` during the build script of TestImages.

**Comment by SimonDanisch** [comment] 2015-09-26 18:50
Just ran into this as well:
https://ci.appveyor.com/project/SimonDanisch/devil-jl/build/1.0.5

**Comment by hayd** [comment] 2015-10-01 16:49
Doing a partial fix here I get stuck with the following line, which seems to read nothing  (and hence throws an error). https://github.com/fhs/ZipFile.jl/blob/83278d3c84efd42262d7dbd494c1869e7823e724/test/runtests.jl#L94

**Comment by tkelman** [comment] 2015-10-02 22:32
The change which caused the failure here on nightlies fixed a base julia precompilation bug, so I'm considering backporting it for 0.4.0-rc4 despite the fact that it's slightly breaking this package. If we don't get a response from the maintainer soon, someone who uses the package may want to fork it for easier collaboration? Maybe JuliaIO could be a home for this?

**Comment by hayd** [comment] 2015-10-02 22:38
ping @fhs, JuliaIO may make sense either way - it's a pretty core package.

**Comment by fhs** [comment] 2015-10-02 23:12
I'm not sure I understand the problem exactly. I've merged #19 but I don't know if that was all you needed. I don't have an OS X machine to test this on.

If julia releases depend on this package, then yes, you should fork it. You can't expect package maintainers to respond immediately. I try to respond to issues within a week.

**Comment by hayd** [comment] 2015-10-02 23:24
```
julia> Pkg.test("ZipFile")
INFO: Testing ZipFile
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.Nothing is deprecated, use Void instead.
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
while loading /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl, in expression starting on line 144
WARNING: Base.Nothing is deprecated, use Void instead.
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
while loading /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl, in expression starting on line 144
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
while loading /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl, in expression starting on line 166
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
while loading /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl, in expression starting on line 171
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
while loading /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl, in expression starting on line 224
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.None is deprecated, use Union{} instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.String is deprecated, use AbstractString instead.
WARNING: Base.None is deprecated, use Union{} instead.
in _find_enddiroffset at /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl:231
WARNING: Base.None is deprecated, use Union{} instead.
in _find_enddiroffset at /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl:236
WARNING: Base.None is deprecated, use Union{} instead.
in _find_enddiroffset at /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl:250
ERROR: LoadError: MethodError: `_find_diroffset` has no method matching _find_diroffset(::IOStream, ::Type{Union{}})
Closest candidates are:
  _find_diroffset(::IO, ::Integer)
 in call at /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl:105
 in call at /Users/andy/.julia/v0.5/ZipFile/src/ZipFile.jl:112
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
while loading /Users/andy/.julia/v0.5/ZipFile/test/runtests.jl, in expression starting on line 22
================================================================================[ ERROR: ZipFile ]================================================================================

failed process: Process(`/Users/andy/projects/julia/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /Users/andy/.julia/v0.5/ZipFile/test/runtests.jl`, ProcessExited(1)) [1]

==================================================================================================================================================================================
ERROR: ZipFile had test errors
```

The error is from [this line](https://github.com/fhs/ZipFile.jl/blob/83278d3c84efd42262d7dbd494c1869e7823e724/test/runtests.jl#L94) as

    read(dir.files[1], @compat(UInt8), length(s1)) == nothing

Note sure why this is the case... I thought that travis/Linux also demonstrated this.

**Comment by hayd** [comment] 2015-10-03 01:08
I think this is to do with difference between Zipfile's read (which works) and io's read! (which doesn't) which is called by the parent read function defined in io during this test.

I tried fixing it by defining read! but this has a side-effect of giving a StackOverflow for fileequals, which I can't quite fix, hopefully there's not a julia 0.4 bug under here...

**Comment by tkelman** [comment] 2015-10-03 01:15
Whether or not we fork or move the package somewhere more people can help in merging fixes to it, need to figure out a fix for the problem first. What could also help is if you would be willing to grant collaborator access to a few people who need to use the package and can help maintain it. As long as you haven't completely disappeared (which happens unfortunately often), it's totally understandable that you're busy and can't get to things immediately.

**Comment by fhs** [comment] 2015-10-03 01:17
I was able to reproduce the problem in Linux.

Basically, the failure is happening because it can't find the offset of the zip metadata at the end of the file. _find_enddiroffset returns None when it should return the offset (a number). I'm still investigating, but it does look like a Julia bug.

**Comment by fhs** [comment] 2015-10-03 01:34
@tkelman I just added you as collaborator. Anyone else want collaborator access, preferably people who follow julia development closely?

**Comment by tkelman** [comment] 2015-10-03 01:40
Thanks! Both @timholy and @SimonDanisch follow julia very closely and noticed the issue before I did,  probably due to working on packages that depend on this one.

**Comment by fhs** [comment] 2015-10-03 01:43
Ok, I've added them as collaborators.

**Comment by fhs** [comment] 2015-10-03 02:37
It's a Julia bug. The following program demonstrates the bug:
```
function f()
	offset = None
	for x in [1, 2]
		if ~is(offset, None)
			break
		end
		offset = 1	# not reached!
	end
	print("f: offset is ", offset, "\n")
end

function g()
	offset = None
	if is(offset, None)
		offset = 1
	end
	print("g: offset is ", offset, "\n")
end

f()
g()
```
It prints this (if I ignore all the warnings):
```
f: offset is Union{}
g: offset is 1
```

**Comment by tkelman** [comment] 2015-10-03 03:17
Looks like. Changing the comparison from `None` to `nothing` fixes the wrong output, but doesn't fix the ZipFile tests. There's an unrelated issue with base Julia right now, see https://github.com/JuliaLang/julia/issues/13399, so nightlies will fail with a certificate problem and this needs to be tested locally.

**Comment by hayd** [comment] 2015-10-05 01:06
This can be closed.

**Closed** 2015-10-05 01:07 UTC
