### ISSUE TITLE
Files bigger than 4 GB seems to fail

### ISSUE THREAD

**Issue by elchudi** [fhs/ZipFile.jl#83] opened 2021-11-01 15:17 UTC
julia 1.6.3
ZipFile v0.9.4
Repro steps:
```
wget https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_30s_tmin.zip
```
```
using ZipFile
zf = ZipFile.Reader("./wc2.1_30s_tmin.zip")
```
I get the error
```

ERROR: invalid file header
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] _getfiles(io::IOStream, diroffset::UInt32, nfiles::UInt16)
   @ ZipFile ~/.julia/packages/ZipFile/evaHP/src/ZipFile.jl:309
 [3] Reader
   @ ~/.julia/packages/ZipFile/evaHP/src/ZipFile.jl:106 [inlined]
 [4] ZipFile.Reader(filename::String)
   @ ZipFile ~/.julia/packages/ZipFile/evaHP/src/ZipFile.jl:118
 [5] top-level scope
   @ REPL[3]:1
```
I think the error comes from line 290 where it says 
```    
offset = readle(io, UInt32)
```
since a UInt32 < 4 GB and the file is bigger

**Comment by fhs** [comment] 2021-11-07 03:56
ZIP64 support is missing. Duplicate of #56.

**Closed by fhs** 2021-11-07 03:56 UTC
